### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by Jimmy-Z** [iliak/OneDownloader#1]
Login to 1fichier.com...
11-08-2016 02:48:56
xxx.rar
Traceback (most recent call last):
  File "/usr/bin/onefichier", line 461, in <module>
    main(sys.argv[1:])
  File "/usr/bin/onefichier", line 451, in main
    one.downloadFile(file)
  File "/usr/bin/onefichier", line 207, in downloadFile
    response = self.session.get(url, headers=headers, stream=True)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 483, in get
    return self.request('GET', url, *_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 471, in request
    resp = self.send(prep, *_send_kwargs)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 575, in send
    adapter = self.get_adapter(url=request.url)
  File "/usr/local/lib/python3.5/site-packages/requests/sessions.py", line 649, in get_adapter
    raise InvalidSchema("No connection adapters were found for '%s'" % url)
requests.exceptions.InvalidSchema: No connection adapters were found for '<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">
<html>
        <head>
    <title>1fichier.com: Cloud Storage</title>
                <meta name="robots" content="noindex" />
    <meta http-equiv="content-type" content="text/html'

seems website has changed

**Comment by iliak** [comment]
Hi,
Please try the dev branch...
